version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - J-Melon
    reviewers:
      - J-Melon
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    assignees:
      - J-Melon
    reviewers:
      - J-Melon
    labels:
      - dependencies
      - python
