version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - J-Melon
    reviewers:
      - J-Melon
    labels:
      - zaphod-dep
      - zaphod-dep-action
    rebase-strategy: disabled

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    assignees:
      - J-Melon
    reviewers:
      - J-Melon
    labels:
      - zaphod-dep
      - zaphod-dep-pip
    rebase-strategy: disabled
