repos:
  - repo: local
    hooks:
      - id: gdformat
        name: gdformat
        entry: gdformat
        language: system
        types: [file]
        files: '\.gd$'
        exclude: '^addons/'
      - id: gdlint
        name: gdlint
        entry: gdlint
        language: system
        types: [file]
        files: '\.gd$'
        exclude: '^addons/'
