default_install_hook_types: [pre-commit]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: gdformat
        name: gdformat
        entry: bash -c 'gdformat "$@" && git add "$@"' --
        language: system
        types: [file]
        files: '\.gd$'
        exclude: '^addons/'
      - id: gdlint
        name: gdlint
        entry: gdlint
        language: system
        types: [file]
        files: '\.gd$'
        exclude: '^addons/'
      - id: gut-tests
        name: gut tests
        entry: godot --headless -s addons/gut/gut_cmdln.gd
        language: system
        pass_filenames: false
        files: '\.gd$'
        exclude: '^addons/'
