name: Publish Game Test to Itch.io

on:
  workflow_dispatch:

env:
  GODOT_VERSION: "4.6.1"

jobs:
  export:
    name: Export Web
    runs-on: ubuntu-latest
    outputs:
      build_directory: ${{ steps.export.outputs.build_directory }}
    steps:
      - uses: actions/checkout@v5

      - name: Export Web
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz"
          relative_project_path: ./

  publish:
    name: Publish to Itch.io
    needs: export
    runs-on: ubuntu-latest
    steps:
      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler

      - name: Push to Itch.io
        run: ./butler push "${{ needs.export.outputs.build_directory }}" Speedyoshi/game-test:html5
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
